sudo: false

language: python

python: 3.5

install:
  - pip install tox-travis
  - pip install codeclimate-test-reporter

script: tox -e functional

after_failure:
  - codeclimate-test-reporter

after_sucess:
  - codeclimate-test-reporter
